---
climate:
  morning:
    fans:
      - area: "Master Suite"
        percentage: 30
      - area: "Living Room"
        percentage: 30
      - area: "Guest Suite"
        percentage: 30
  day:
    fans:
      - area: "Master Suite"
        percentage: 30
      - area: "Living Room"
        percentage: 70
      - area: "Guest Suite"
        percentage: 70
  sunset:
    fans:
      - area: "Master Suite"
        percentage: 40
      - area: "Living Room"
        percentage: 70
      - area: "Guest Suite"
        percentage: 70
  dusk:
    fans:
      - area: "Master Suite"
        percentage: 40
      - area: "Living Room"
        percentage: 70
      - area: "Guest Suite"
        percentage: 70
  winddown:
    fans:
      - area: "Master Suite"
        percentage: 70
      - area: "Living Room"
        percentage: 70
      - area: "Guest Suite"
        percentage: 70
  night:
    fans:
      - area: "Master Suite"
        percentage: 70
      - area: "Living Room"
        percentage: 10
      - area: "Guest Suite"
        percentage: 70
