---
rooms:
  - hue_group: Living Room
    hass_area_id: living_room_2
    off_if_true: isEveryoneAsleep
    increase_brightness_if_true: isHaveGuests
  - hue_group: Primary Suite
    hass_area_id: master_bedroom
    off_if_true: isMasterAsleep
  - hue_group: Dining Room
    hass_area_id: dining_room
    off_if_true: isEveryoneAsleep
    increase_brightness_if_true: isHaveGuests
