---
music:
  morning:
    participants:
      - player_name: "Kitchen"
        base_volume: 9
        leave_muted_if: []
      - player_name: "Soundbar"
        base_volume: 10
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Kids Bathroom"
        base_volume: 7
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 9
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 8
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 8
        leave_muted_if:
          - variable: isNickOfficeOccupied
            value: false
    playback_options:
      # Instrumental Melodic House and Techno
      - uri: spotify:playlist:62CFZGi01r81y81tSuj155
        media_type: playlist
        volume_multiplier: 1.0
      # Instrumental Techno Mix
      - uri: spotify:playlist:37i9dQZF1EIgBWjkyfXHmo
        media_type: playlist
        volume_multiplier: 1.0
      # Instrumental House Mix
      - uri: spotify:playlist:37i9dQZF1EIhris6SwzGuN
        media_type: playlist
        volume_multiplier: 1.0
      # Epic Classical
      - uri: spotify:playlist:37i9dQZF1E4vSnB7GD9Gct
        media_type: playlist
        volume_multiplier: 1.0
  day:
    participants:
      - player_name: "Kitchen"
        base_volume: 9
        leave_muted_if: []
      - player_name: "Soundbar"
        base_volume: 10
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Kids Bathroom"
        base_volume: 7
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 9
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 9
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 6
        leave_muted_if:
          - variable: isNickOfficeOccupied
            value: false
    playback_options:
      # Kygo Radio
      - uri: spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        media_type: playlist
        volume_multiplier: 1.0
      # Chill Tracks
      - uri: spotify:playlist:37i9dQZF1DX6VdMW310YC7
        media_type: playlist
        volume_multiplier: 1.0
      # Lounge - Soft House
      - uri: spotify:playlist:37i9dQZF1DX82pCGH5USnM
        media_type: playlist
        volume_multiplier: 1.0
      # Caroline's country playlist
      - uri: spotify:playlist:5Wyuc2BN76JyKioxcaY7ud
        media_type: playlist
        volume_multiplier: 1.0
      # Summer Party
      - uri: spotify:playlist:37i9dQZF1DX5Ozry5U6G0d
        media_type: playlist
        volume_multiplier: 1.0
      # Lowkey tech
      - uri: spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        media_type: playlist
        volume_multiplier: 1.0
      # Kygo Radio
      - uri: spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        media_type: playlist
        volume_multiplier: 1.0
      # Blockheady Instrumental
      - uri: spotify:playlist:7hw5bkUl4xLPDCymveIfnK
        media_type: playlist
        volume_multiplier: 1.0
  evening:
    participants:
      - player_name: "Kitchen"
        base_volume: 9
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Kids Bathroom"
        base_volume: 8
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 10
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 8
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 8
        leave_muted_if:
          - variable: isNickOfficeOccupied
            value: false
    playback_options:
      # Instrumental Study
      - uri: spotify:playlist:37i9dQZF1DX9sIqqvKsjG8
        media_type: playlist
        volume_multiplier: 1.2
      # Jazz in the background
      - uri: spotify:playlist:37i9dQZF1DWV7EzJMK2FUI
        media_type: playlist
        volume_multiplier: 1.0
      # This is Hilary Hahn
      - uri: spotify:playlist:37i9dQZF1DZ06evO3ngxkl
        media_type: playlist
        volume_multiplier: 1.5
      # Blowin' in the wind radio
      - uri: spotify:playlist:37i9dQZF1E8Q7fAfKoKDtW
        media_type: playlist
        volume_multiplier: 1.0
      # Calming Classical (Needs much higher volumes for parity)
      - uri: spotify:playlist:37i9dQZF1DWVFeEut75IAL
        media_type: playlist
        volume_multiplier: 1.5
      # Chilled Jazz
      - uri: spotify:playlist:37i9dQZF1DX2vYju3i0lNX
        media_type: playlist
        volume_multiplier: 1.0
      # Instrumental Classical
      - uri: spotify:playlist:5fSuIObNY9SB8gUMt1xrsB
        media_type: playlist
        volume_multiplier: 1.0
  winddown:
    participants:
      - player_name: "Kitchen"
        base_volume: 10
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Kids Bathroom"
        base_volume: 8
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 10
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 7
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 8
        leave_muted_if:
          - variable: isNickOfficeOccupied
            value: false
    playback_options:
      # Floating Through Space
      - uri: spotify:playlist:37i9dQZF1DX1n9whBbBKoL
        media_type: playlist
        volume_multiplier: 1.0
      # Ambient Relaxation
      - uri: spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
        media_type: playlist
        volume_multiplier: 1.0
      # Sleep
      - uri: spotify:playlist:37i9dQZF1DWZd79rJ6a7lp
        media_type: playlist
        volume_multiplier: 1.0
  sleep:
    participants:
      - player_name: "Bedroom"
        base_volume: 16
        leave_muted_if: []
      - player_name: "Dining Room"
        base_volume: 9
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Kitchen"
        base_volume: 16
        leave_muted_if: []
      - player_name: "Office"
        base_volume: 9
        leave_muted_if:
          - variable: isNickOfficeOccupied
            value: false
    playback_options:
      - uri: "http://rain-sounds.nickborgers.net:8080/1.m4a"
        media_type: music
        volume_multiplier: 1.1
      - uri: "http://rain-sounds.nickborgers.net:8080/2.m4a"
        media_type: music
        volume_multiplier: 1.0
      - uri: "http://rain-sounds.nickborgers.net:8080/4.m4a"
        media_type: music
        volume_multiplier: 0.8
  sex:
    participants:
      - player_name: "Bedroom"
        base_volume: 10
        leave_muted_if: []
    playback_options:
      - uri: spotify:playlist:1WaopApISE1aAT83aIYKRw
        media_type: playlist
        volume_multiplier: 1.0
  wakeup:
    participants:
      - player_name: "Bedroom"
        base_volume: 6
        leave_muted_if: []
    playback_options:
      # Ambient Relaxation
      - uri: spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
        media_type: playlist
        volume_multiplier: 1.0
