---
music:
  morning:
    participants:
      - player_name: "Kitchen"
        base_volume: 11
        leave_muted_if: []
      - player_name: "Soundbar"
        base_volume: 9
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Kids Bathroom"
        base_volume: 9
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 9
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 8
        leave_muted_if: []
    playback_options:
      # Instrumental Melodic House and Techno
      - uri: spotify:user:spotify:playlist:62CFZGi01r81y81tSuj155
        volume_multiplier: 1.0
      # Instrumental Techno Mix
      - uri: spotify:user:spotify:playlist:37i9dQZF1EIgBWjkyfXHmo
        volume_multiplier: 1.0
      # Instrumental House Mix
      - uri: spotify:user:spotify:playlist:37i9dQZF1EIhris6SwzGuN
        volume_multiplier: 1.0
      # Epic Classical
      - uri: spotify:user:spotify:playlist:37i9dQZF1E4vSnB7GD9Gct
        volume_multiplier: 1.0
  day:
    participants:
      - player_name: "Kitchen"
        base_volume: 10
        leave_muted_if: []
      - player_name: "Soundbar"
        base_volume: 11
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Kids Bathroom"
        base_volume: 10
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 10
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 10
        leave_muted_if: []
    playback_options:
      # Kygo Radio
      - uri: spotify:user:spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        volume_multiplier: 1.0
      # Chill Tracks
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX6VdMW310YC7
        volume_multiplier: 1.0
      # Lounge - Soft House
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX82pCGH5USnM
        volume_multiplier: 1.0
      # Caroline's country playlist
      - uri: spotify:user:spotify:playlist:5Wyuc2BN76JyKioxcaY7ud
        volume_multiplier: 1.0
      # Summer Party
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX5Ozry5U6G0d
        volume_multiplier: 1.0
      # Lowkey tech
      - uri: spotify:user:spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        volume_multiplier: 1.0
      # Owl City
      - uri: spotify:user:spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        volume_multiplier: 1.0
      # Blockheady Instrumental
      - uri: spotify:user:spotify:playlist:7hw5bkUl4xLPDCymveIfnK
        volume_multiplier: 1.0
  evening:
    participants:
      - player_name: "Kitchen"
        base_volume: 13
        leave_muted_if: []
      - player_name: "Kids Bathroom"
        base_volume: 12
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 15
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 12
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 12
        leave_muted_if: []
    playback_options:
      # Instrumental Study
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX9sIqqvKsjG8
        volume_multiplier: 1.2
      # Jazz in the background
      - uri: spotify:user:spotify:playlist:37i9dQZF1DWV7EzJMK2FUI
        volume_multiplier: 1.0
      # This is Hilary Hahn
      - uri: spotify:user:spotify:playlist:37i9dQZF1DWV15rjiWJsBI
        volume_multiplier: 1.5
      # Blowin' in the wind radio
      - uri: spotify:user:spotify:playlist:37i9dQZF1E8Q7fAfKoKDtW
        volume_multiplier: 1.0
      # Calming Classical (Needs much higher volumes for parity)
      - uri: spotify:user:spotify:playlist:37i9dQZF1DWVFeEut75IAL
        volume_multiplier: 1.5
      # Chilled Jazz
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX2vYju3i0lNX
        volume_multiplier: 1.0
      # Instrumental Classical
      - uri: spotify:user:spotify:playlist:5fSuIObNY9SB8gUMt1xrsB
        volume_multiplier: 1.0
  winddown:
    participants:
      - player_name: "Kitchen"
        base_volume: 15
        leave_muted_if: []
      - player_name: "Kids Bathroom"
        base_volume: 12
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Bedroom"
        base_volume: 15
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Dining Room"
        base_volume: 12
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Office"
        base_volume: 12
        leave_muted_if: []
    playback_options:
      # Floating Through Space
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX1n9whBbBKoL
        volume_multiplier: 1.0
      # Ambient Relaxation
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
        volume_multiplier: 1.0
      # Sleep
      - uri: spotify:user:spotify:playlist:37i9dQZF1DWZd79rJ6a7lp
        volume_multiplier: 1.0
  sleep:
    participants:
      - player_name: "Bedroom"
        base_volume: 25
        leave_muted_if: []
      - player_name: "Dining Room"
        base_volume: 25
        leave_muted_if:
          - variable: isTVPlaying
            value: true
      - player_name: "Kitchen"
        base_volume: 25
        leave_muted_if: []
      - player_name: "Office"
        base_volume: 25
        leave_muted_if: []
    playback_options:
      - uri: "Local Rain Track 1"
        volume_multiplier: 1.4
      - uri: "Local Rain Track 2"
        volume_multiplier: 1.0
      - uri: "Local Rain Track 3"
        volume_multiplier: 1.32
      - uri: "Local Rain Track 4"
        volume_multiplier: 1.6
      - uri: "Local Rain Track 5"
        volume_multiplier: 1.18
  sex:
    participants:
      - player_name: "Bedroom"
        base_volume: 18
        leave_muted_if: []
    playback_options:
      - uri: spotify:user:spotify:playlist:1WaopApISE1aAT83aIYKRw
        volume_multiplier: 1.0
  wakeup:
    participants:
      - player_name: "Bedroom"
        base_volume: 50
        leave_muted_if: []
    playback_options:
      # Ambient Relaxation
      - uri: spotify:user:spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
        volume_multiplier: 1.0
