---
music:
  morning:
    participants:
      - player_name: "Nook Speaker"
        default_volume: 11
        leave_muted_if: []
      - player_name: "Living Room"
        default_volume: 9
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Guest Bathroom"
        default_volume: 9
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 9
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 8
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
    playback_options:
      # Instrumental Melodic House and Techno
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:62CFZGi01r81y81tSuj155
        volume_multiplier: 1.0
      # Instrumental Techno Mix
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1EIgBWjkyfXHmo
        volume_multiplier: 1.0
      # Instrumental House Mix
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1EIhris6SwzGuN
        volume_multiplier: 1.0
      # Epic Classical
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1E4vSnB7GD9Gct
        volume_multiplier: 1.0
  day:
    participants:
      - player_name: "Nook Speaker"
        default_volume: 10
        leave_muted_if: []
      - player_name: "Living Room"
        default_volume: 11
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Guest Bathroom"
        default_volume: 10
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 10
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 10
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
          - variable: isNickHome
            value: false
    playback_options:
      # Kygo Radio
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        volume_multiplier: 1.0
      # Chill Tracks
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX6VdMW310YC7
        volume_multiplier: 1.0
      # Lounge - Soft House
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX82pCGH5USnM
        volume_multiplier: 1.0
      # Caroline's country playlist
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:5Wyuc2BN76JyKioxcaY7ud
        volume_multiplier: 1.0
      # Summer Party
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX5Ozry5U6G0d
        volume_multiplier: 1.0
      # Lowkey tech
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        volume_multiplier: 1.0
      # Owl City
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1E4zvzTbEfkwF2
        volume_multiplier: 1.0
  evening:
    participants:
      - player_name: "Nook Speaker"
        default_volume: 13
        leave_muted_if: []
      - player_name: "Living Room"
        default_volume: 15
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Guest Bathroom"
        default_volume: 12
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 15
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 12
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
          - variable: isNickHome
            value: false
    playback_options:
      # Instrumental Study
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX9sIqqvKsjG8
        volume_multiplier: 1.2
      # Jazz in the background
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWV7EzJMK2FUI
        volume_multiplier: 1.0
      # This is Hilary Hahn
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWV15rjiWJsBI
        volume_multiplier: 1.5
      # Blowin' in the wind radio
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1E8Q7fAfKoKDtW
        volume_multiplier: 1.0
      # Calming Classical (Needs much higher volumes for parity)
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWVFeEut75IAL
        volume_multiplier: 1.5
      # Chilled Jazz
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX2vYju3i0lNX
        volume_multiplier: 1.0
      # Instrumental Classical
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:5fSuIObNY9SB8gUMt1xrsB
        volume_multiplier: 1.5
  winddown:
    participants:
      - player_name: "Nook Speaker"
        default_volume: 15
        leave_muted_if: []
      - player_name: "Living Room"
        default_volume: 15
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Guest Bathroom"
        default_volume: 12
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 15
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 12
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
          - variable: isNickHome
            value: false
    playback_options:
      # Floating Through Space
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX1n9whBbBKoL
        volume_multiplier: 1.0
      # Ambient Relaxation
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
        volume_multiplier: 1.0
      # Sleep
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWZd79rJ6a7lp
        volume_multiplier: 1.0
  sleep:
    participants:
      - player_name: "Nook Speaker"
        default_volume: 40
        leave_muted_if:
          - variable: isHaveGuests
            value: false
      - player_name: "Living Room"
        default_volume: 20
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 35
        leave_muted_if: []
      - player_name: "Master Bedroom"
        default_volume: 38
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 30
        leave_muted_if:
          - variable: isHaveGuests
            value: false
      - player_name: "Guest Bedroom"
        default_volume: 25
        leave_muted_if:
          - variable: isHaveGuests
            value: false
    playback_options:
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/1.m4a"
        volume_multiplier: 1.4
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/3.m4a"
        volume_multiplier: 1.0
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/4.m4a"
        volume_multiplier: 1.32
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/5.m4a"
        volume_multiplier: 1.6
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/6.m4a"
        volume_multiplier: 1.18
  airplay:
    participants:
      - player_name: "Living Room"
        default_volume: 9
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Nook Speaker"
        default_volume: 11
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 9
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
      - player_name: "Master Bedroom"
        default_volume: 12
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 9
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 8
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
    playback_options: []
  sex:
    participants:
      - player_name: "Master Bathroom"
        default_volume: 15
        leave_muted_if: []
      - player_name: "Master Bedroom"
        default_volume: 25
        leave_muted_if: []
    playback_options:
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:6JynmyHkOPxeTryinNymBi
        volume_multiplier: 1.0
  wakeup:
    participants:
      - player_name: "Master Bathroom"
        default_volume: 20
        leave_muted_if: []
      - player_name: "Master Bedroom"
        default_volume: 50
        leave_muted_if: []
    playback_options:
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/birds.m4a"
        volume_multiplier: 1.0
