---
music:
  morning:
    participants:
      - player_name: "Living Room"
        default_volume: 13
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Nook Speaker"
        default_volume: 13
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 17
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 17
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 17
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 10
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
    playback_options:
      # Dance Hits
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX0BcQWzuB7ZO
        volume_multiplier: 1
      # Shuffle Syndrome
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy
        volume_multiplier: 1
      # Housewerk
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DXa8NOEUWPn9W
        volume_multiplier: 1
      # Pop Remix
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DXcZDD7cfEKhW
        volume_multiplier: 1
  day:
    participants:
      - player_name: "Living Room"
        default_volume: 12
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Nook Speaker"
        default_volume: 10
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 17
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 17
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 17
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 17
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
          - variable: isNickHome
            value: false
    playback_options:
      # Chill Tracks
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX6VdMW310YC7
        volume_multiplier: 1
      # Lounge - Soft House
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX82pCGH5USnM
        volume_multiplier: 1
      # Caroline's country playlist
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:5Wyuc2BN76JyKioxcaY7ud
        volume_multiplier: 1
      # Summer Party
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX5Ozry5U6G0d
        volume_multiplier: 1
  evening:
    participants:
      - player_name: "Living Room"
        default_volume: 14
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Nook Speaker"
        default_volume: 13
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 17
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 17
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 17
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 17
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
          - variable: isNickHome
            value: false
    playback_options:
      # Instrumental Study
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX9sIqqvKsjG8
        volume_multiplier: 1.25
      # Jazz in the background
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWV7EzJMK2FUI
        volume_multiplier: 1
      # Blowin' in the wind radio
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1E8Q7fAfKoKDtW
        volume_multiplier: 1
      # Calming Classical (Needs much higher volumes for parity)
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWVFeEut75IAL
        volume_multiplier: 1.6
      # Chilled Jazz
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX2vYju3i0lNX
        volume_multiplier: 1
      # Classical New Releases (Needs much higher volumes for parity)
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWV0gynK7G6pD
        volume_multiplier: 2
  night:
    participants:
      - player_name: "Living Room"
        default_volume: 15
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Nook Speaker"
        default_volume: 20
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 20
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isTVPlaying
            value: true
      - player_name: "Master Bedroom"
        default_volume: 20
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Master Bathroom"
        default_volume: 20
        leave_muted_if:
          - variable: isMasterAsleep
            value: true
      - player_name: "Guest Bedroom"
        default_volume: 20
        leave_muted_if:
          - variable: isGuestAsleep
            value: true
          - variable: isGuestBedroomDoorOpen
            value: false
          - variable: isNickHome
            value: false
    playback_options:
      # Floating Through Space
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX1n9whBbBKoL
        volume_multiplier: 1
      # Ambient Relaxation
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
        volume_multiplier: 1
      # Sleep
      - command: group.queue.urispotify
        uri: spotify:user:spotify:playlist:37i9dQZF1DWZd79rJ6a7lp
        volume_multiplier: 1
  sleep:
    participants:
      - player_name: "Master Bedroom"
        default_volume: 29
        leave_muted_if: []
      - player_name: "Master Bathroom"
        default_volume: 40
        leave_muted_if: []
      - player_name: "Guest Bathroom"
        default_volume: 30
        leave_muted_if: []
    playback_options:
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/1.m4a"
        volume_multiplier: 1.28
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/3.m4a"
        volume_multiplier: 1
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/4.m4a"
        volume_multiplier: 1.14
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/5.m4a"
        volume_multiplier: 1.38
      - command: group.queue.uri
        uri: "http://rain-sounds.nickborgers.com/6.m4a"
        volume_multiplier: 1.51
