name: Publish-Screenshots

on:
  push:
    branches: [ master, add-automated-rendering ]

jobs:
  generate-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Build Docker images
        run: make build
      - name: Generate screenshots
        run: make run-to-generate-screenshots
      - name: Upload screenshots to GitHub Pages
        uses: actions/upload-artifact@v2
        with: 
          name: screenshots
          path: .automated-rendering/screenshot-capture/screenshots/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1