name: Validate-Configs

on:
  push:
    branches: [ '*' ]

jobs:
  validate-music-config-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Validate Music YAML file
        run: make run-yamllint-music
  validate-hue-config-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Validate Hue YAML file
        run: make run-yamllint-hue

  validate-music-config-spotify-uris:
    needs: validate-music-config-yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Run validation script
        run: make run-spotify-validation-music
